# Generated by Django 5.1.6 on 2025-02-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags_note', to='tags.tags'),
        ),
    ]
