# Generated by Django 5.1.6 on 2025-03-09 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_notes_options_notes_create_at_notes_update_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
